#!/usr/bin/env ruby
# frozen_string_literal: true

ENV["GOOGLE_API_KEY"] = "AIzaSyCnCd3Fn28D8eu_g4UgdZ85Y1XQlWlRSlg"

require "bundler/setup"
require "omniai/google"

client = OmniAI::Google::Client.new

puts "> [USER] Who won the most recent NBA Finals?"

response = client.chat("Who won the most recent NBA Finals?", tools: %i[google_search])
puts response.text
