#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "omniai/google"

CLIENT = OmniAI::Google::Client.new

puts "> [USER] Who won the most recent NBA playoffs?"

response = CLIENT.chat("Who won the most recent NBA playoffs?")
puts response.text
